name: Daily Automated Run

on:
  schedule:
    # Runs every day at 5:00 PM UTC (which is after the UK market close at 4:30 PM UTC)
    - cron: '0 17 * * *'

jobs:
  run_daily_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Analysis Script
        run: |
          python app.py